name:                algebraic-foldl
version:             0.1.0.0
github:              "michaeljklein/algebraic-foldl"
license:             BSD3
author:              "Michael J. Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "2018 Michael J. Klein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaeljklein/algebraic-foldl#readme>

dependencies:
- base >= 4.7 && < 5
- adjunctions
- comonad
- constraints
- contravariant
- distributive
- foldl
- free
- ghc-prim
- ghc-typelits-natnormalise
- list-t
- mtl
- profunctors
- semigroupoids
- transformers

library:
  source-dirs: src

tests:
  basic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebraic-foldl
